version: '3'
# networking
# volumes
services:
  fx-control-plane:
    image: "fxlabs/control-plane:latest"
    environment:
      # RabbitMQ
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      # Postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
      # ElasticSearch
      # Redis
    # inject rabbit-host, port, vhost, user-cp, user-cp-pass
    # inject postgres, port, db, user, pass
    # inject elasticsearch, port,
    # inject redis, port
