version: '3'
# networking
# volumes
services:
  #fx-redis:
  #  image: "redis:alpine"

  fx-postgres:
    image: "postgres:9.6.7"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # create db, user, pass

  fx-elasticsearch:
    image: "elasticsearch:5.0.0"
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_MEM}

  fx-rabbitmq:
    image: "rabbitmq:3.7.3-management"
    hostname: fx_rabbitmq_stg
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    # create vhost, user-cp,
    # TODO user-mail, user-sync, user-bot