version: '3'
# networking
# volumes
services:
  fx-bot:
    image: "fxlabs/bot:latest"
    environment:
      # RabbitMQ
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    # inject rabbit-host, port, vhost, user-bot, user-bot-pass

  fx-mail-bot:
    image: "fxlabs/mail-bot:latest"
    environment:
      # RabbitMQ
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    # inject rabbit-host, port, vhost, user-mail, user-mail-pass

  fx-git-sync-bot:
    image: "fxlabs/git-sync-bot:latest"
    environment:
      # RabbitMQ
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    # inject rabbit-host, port, vhost, user-sync, user-sync-pass

  fx-haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 15672:15672
      - 5672:5672
      - 80:80