package com.fxlabs.fxt.dao.repository.es;

import com.fxlabs.fxt.dao.entity.clusters.Account;
import com.fxlabs.fxt.dao.entity.project.ProjectFile;
import com.fxlabs.fxt.dao.entity.project.TestSuiteCategory;
import org.springframework.data.domain.Page;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;

import java.util.List;
import java.util.Optional;

/**
 * @author Intesar Shannan Mohammed
 * @author Mohammed Shoukath Ali
 */
public interface ProjectFileESRepository extends ElasticsearchRepository<ProjectFile, String> {

    Optional<ProjectFile> findByProjectIdAndFilenameIgnoreCase(String projectId, String fileName);

    Page<ProjectFile> findByProjectId(String projectId, org.springframework.data.domain.Pageable pageable);

    void deleteInBatchByProjectIdAndAutoGenerated(String projectId, boolean autoGenerated);

    void deleteInBatchByProjectIdAndCategoryInAndAutoGenerated(String projectId, List<String> category, boolean autoGenerated);
}
